# Generated by Django 3.0.2 on 2020-01-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='CRUDModel',
        ),
    ]
